# fly.toml app configuration file generated for todo-apps on 2025-01-28T18:17:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-apps'
primary_region = 'nrt'
console_command = '/code/manage.py shell'

[build]
  builder = "docker"
  dockerfile = "Dockerfile"
[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
