# fly.toml
app = "todo-apps"
primary_region = "nrt"

image = "registry.fly.io/todo-apps:latest"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
