# Generated by Django 4.2.17 on 2025-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(verbose_name='作成日')),
                ('task1', models.CharField(max_length=150, verbose_name='タスク1')),
                ('task2', models.CharField(max_length=150, verbose_name='タスク2')),
                ('task3', models.CharField(max_length=150, verbose_name='タスク3')),
            ],
        ),
    ]
