# Generated by Django 4.2.17 on 2025-01-22 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriorityTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritytask',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 19, 44, 34, 775342), verbose_name='作成日'),
        ),
    ]
