# Generated by Django 4.2.17 on 2025-01-22 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriorityTask', '0002_alter_prioritytask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritytask',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 19, 50, 27, 241766), verbose_name='作成日'),
        ),
    ]
