# Generated by Django 4.2.17 on 2025-02-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriorityTask', '0004_alter_prioritytask_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritytask',
            name='task1',
            field=models.CharField(max_length=150, verbose_name='task 1'),
        ),
        migrations.AlterField(
            model_name='prioritytask',
            name='task2',
            field=models.CharField(max_length=150, verbose_name='task 2'),
        ),
        migrations.AlterField(
            model_name='prioritytask',
            name='task3',
            field=models.CharField(max_length=150, verbose_name='task 3'),
        ),
    ]
