# Generated by Django 4.2.17 on 2025-02-04 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PriorityTask', '0005_alter_prioritytask_task1_alter_prioritytask_task2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritytask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='priority_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
