# Generated by Django 4.2.17 on 2025-02-02 05:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='習慣名')),
                ('target_day_per_week', models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='週に行うべき回数')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='作成')),
                ('completed', models.BooleanField(default=False, verbose_name='達成')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Habit.habit')),
            ],
            options={
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
