# Generated by Django 4.2.17 on 2025-02-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateTimeField(verbose_name='作成'),
        ),
    ]
