# Generated by Django 4.2.17 on 2025-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0002_alter_habitlog_created_at_alter_habitlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(verbose_name='作成'),
        ),
    ]
