# Generated by Django 4.2.17 on 2025-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0004_alter_habit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
