# Generated by Django 4.2.17 on 2025-02-04 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0006_alter_habit_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='habit name'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_day_per_week',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(7)], verbose_name='times per week'),
        ),
    ]
