# Generated by Django 4.2.17 on 2025-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0008_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='successful'),
        ),
    ]
