# Generated by Django 4.2.17 on 2025-02-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0009_habit_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='completed',
            new_name='successful',
        ),
    ]
