# Generated by Django 4.2.17 on 2025-02-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Habit', '0010_rename_completed_habit_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='successful_date',
            field=models.DateField(blank=True, null=True, verbose_name='successful date'),
        ),
    ]
